# Generated by Django 3.2.22 on 2024-06-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Junior Basic', '初级 基础'), ('Junior Plus', '初级 进阶'), ('Junior Ultra', '初级 强化'), ('Intermediate Basic', '中级 基础'), ('Intermediate Plus', '中级 进阶'), ('Intermediate Ultra', '中级 强化'), ('Senior Basic', '高级 基础'), ('Senior Plus', '高级 进阶'), ('Senior Ultra', '高级 强化')], max_length=20, unique=True)),
                ('skill_training', models.IntegerField()),
                ('problem_solving', models.IntegerField()),
                ('competition_guidance', models.IntegerField()),
                ('camp', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
